# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353f9c149de34db566d1337bfa65302411e3986461a7b3d49dd766beab04207aec349edc63d155e4591bf7eaa6b798a6fce48451aa79a5a2b3e7ae5047a24959

test:
  secret_key_base: 9cc25b8bd3fe5f3287fb81090589fbe18aba01a486cadfbf8de8bf54fa6faec8768459cdc6ffc3f3896ef402b2d0ed687b51bcffad7c81ab402bc24edaef36d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
